version: '3.8'
services:
  postgres:
    container_name: postgres-springboot-camel
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-springboot-camel
    volumes:
#      - ./data:/var/lib/postgresql/data
      - /Volumes/Macintosh-User/db_test_directory/postgres_data_dir/:/var/lib/postgresql/data
#      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-springboot-camel
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sauravsavarn@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    restart: unless-stopped

#volumes:
#  postgres-data: