spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel

startRoute: timer:CamelRoutingWithProfiles?period=10s
#fromRoute: file:data/dev/input?delete=true&readLock=none
#toRoute1:  file:data/dev/output
fromRoute: file:data/inputUsingProfiles?delete=true&readLock=none
startRouteForDBImpl: timer:CamelRouteWithProfilesAndDBImpl?period=10s
fromRouteForDBImpl: file:data/inputUsingProfilesAndDBImpl?delete=true&readLock=none
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: DEV environment
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel

startRoute: timer:CamelRoutingWithProfiles?period=10s
#fromRoute: file:data/stage/input?delete=true&readLock=none
#toRoute1:  file:data/stage/output
fromRoute: file:data/inputUsingProfiles?delete=true&readLock=none
startRouteForDBImpl: timer:CamelRouteWithProfilesAndDBImpl?period=10s
fromRouteForDBImpl: file:data/inputUsingProfilesAndDBImpl?delete=true&readLock=none
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: STAGE environment
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel

startRoute: timer:CamelRoutingWithProfiles?period=10s
#fromRoute: file:data/prod/input?delete=true&readLock=none
#toRoute1:  file:data/prod/output
fromRoute: file:data/inputUsingProfiles?delete=true&readLock=none
startRouteForDBImpl: timer:CamelRouteWithProfilesAndDBImpl?period=10s
fromRouteForDBImpl: file:data/inputUsingProfilesAndDBImpl?delete=true&readLock=none
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: PROD environment
---