spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
  mail:
    host: smtp.gmail.com
    port: 587
    username: savarn.learning@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mailTo: sauravsavarn@gmail.com
mailFrom: savarn.learning@gmail.com

startRoute: timer:CamelRoute?period=10s
fromRoute: file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: DEV environment
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
  mail:
    host: smtp.gmail.com
    port: 587
    username: savarn.learning@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mailTo: sauravsavarn@gmail.com
mailFrom: savarn.learning@gmail.com

startRoute: timer:CamelRoute?period=10s
fromRoute: file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: STAGE environment
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres-springboot-camel
  mail:
    host: smtp.gmail.com
    port: 587
    username: savarn.learning@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mailTo: sauravsavarn@gmail.com
mailFrom: savarn.learning@gmail.com

startRoute: timer:CamelRoute?period=10s
fromRoute: file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1:  file:data/output
toRoute2:  jdbc:dataSource #toRoute2 is the route to the database
toRoute3:  file:data/output?fileName=Success.txt #signify toRoute SUCCESS is logged into.

message: PROD environment
---